# version: '3'


# services: 
#   web:
#     build: .
#     command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#     volumes: 
#       - .:/code
#     ports:
#       - "8000:8000"


# version: '3'

# services:
#   web:
#     build: .
#     command: bash -c "python3 manage.py collectstatic --no-input &&   
#             python3 manage.py makemigrations &&             
#             python3 manage.py migrate &&
#             python manage.py runserver 0.0.0.0:8000 "                             
#     volumes:
#       - .:/code
#       - db-data:/var/lib/sqlite
#     ports:
#       - "8000:8000"

# volumes:
#   db-data:

version: '3'

services:
  web:
    build: .
    command: bash -c "python3 manage.py collectstatic --no-input &&   
            python3 manage.py makemigrations &&             
            python3 manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000 "                             
    volumes:
      - .:/code
      - db-data:/var/lib/sqlite
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A newcelery worker --loglevel=info

volumes:
  db-data:

