# Generated by Django 4.2.4 on 2023-11-21 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositoption',
            name='joined_users',
            field=models.ManyToManyField(related_name='my_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='like_users',
            field=models.ManyToManyField(related_name='like_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingoption',
            name='joined_users',
            field=models.ManyToManyField(related_name='my_savings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingproduct',
            name='like_users',
            field=models.ManyToManyField(related_name='like_savings', to=settings.AUTH_USER_MODEL),
        ),
    ]
