# Generated by Django 4.2.4 on 2023-11-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.TextField()),
                ('cur_nm', models.TextField()),
                ('bkpr', models.IntegerField()),
                ('last_saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
